config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"

  resources :products
  resources :categories, only: [:show]
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete :cancel     # orders/id/cancel
      post :pay          # orders/id/pay
      get :pay_confirm   # orders/id/pay_confirm
    end
    
    collection do
      get :confirm       # orders/confirm
    end
  end

  namespace :admin do
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort
      end
    end
  end

  # api/v1/subscribe
  namespace :api do
    namespace :v1 do
      post :subscribe, to: "utils#subscribe"
      post :cart, to: "utils#cart"
    end
  end
end

app/views/shared/frontend/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_pack_tag 'cats/1.jpg', class: "d-block w-100 height-400" %>
    </div>
    <div class="carousel-item">
      <%= image_pack_tag 'cats/2.jpg', class: "d-block w-100 height-400" %>
    </div>
    <div class="carousel-item">
      <%= image_pack_tag 'cats/3.jpg', class: "d-block w-100 height-400" %>
    </div>
    <div class="carousel-item">
      <%= image_pack_tag 'cats/4.jpg', class: "d-block w-100 height-400" %>
    </div>
    <div class="carousel-item">
      <%= image_pack_tag 'cats/5.jpg', class: "d-block w-100 height-400" %>
    </div>
    <div class="carousel-item">
      <%= image_pack_tag 'cats/6.jpg', class: "d-block w-100 height-400" %>
    </div>
  </div>
  

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/shared/frontend/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-5">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mx-auto">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">GETBUY</h5>
        <p class="font-weight-bold"><i class="fas fa-map-marked-alt"></i>&nbsp; Tapei, Taiwan</p>
        <p class="font-weight-bold"><i class="fas fa-phone-square"></i>&nbsp; +886(02)234567890</p>
        <p></p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">About Us</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">Our Team</a>
          </li>
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">Customers</a>
          </li>
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">Partnership</a>
          </li>
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">Privacy Policy</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Resources</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">Contacts</a>
          </li>
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">Price</a>
          </li>
          <li>
            <a href="#!" class="font-weight-bold text-decoration-none text-dark">F&Q</a>
          </li>
        </ul>

      </div>
    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <hr>

  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fab fa-google-plus-g"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fab fa-linkedin-in"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-dribbble mx-1">
        <i class="fab fa-dribbble"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> getbuy.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow-sm bg-white sticky-top">
  <a class="navbar-brand" href="/">
    <%= image_pack_tag "logo.jpg", height: "35px" %>
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-green my-2 my-sm-0" type="submit">
        <i class="fas fa-search"></i> 
      </button>
    </form>
    
    <ul class="navbar-nav ml-auto">
      <li class="nav-item" data-controller="cart">
        <%= link_to cart_path, class: "nav-link" do %>
          <i class="fas fa-shopping-cart"></i>
          <span data-target="cart.count" data-action="addToCart@document->cart#updateCart">
            (<%= current_cart.items.count %>)
          </span>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <% if current_user.username? %>
              <%= current_user.username %>
            <% else %>
              <%= current_user.email.split('@').first %>
            <% end %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", admin_products_path, class: "dropdown-item" if current_user.admin? %>
            <%= link_to "Payment Record", orders_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete,
                                   data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "LogIn", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "SignUp", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    
  </div>
</nav>

app/views/shared/frontend/_product_list.html.erb
<section class="product_list container">
  <div class="row">
    <div class="col-12">
      <div class="row justify-content-around">
        <% products.each do |product| %>
          <%= link_to product_path(product), class: "text-dark text-decoration-none" do %>
            <div class="col-4 mt-3">
              <div class="card" style="width: 18rem;">
                <%= image_tag product.cover_image, class: "card-img-top" if product.cover_image.attached? %>
                <div class="card-body">
                  <h5 class="card-title"><%= product.vendor.title %></h5>
                  <p class="card-text"><%= product.name %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shared/frontend/_subscribe.html.erb
<section class="subscribe p-4 mb-2 mb-3 bg-light text-dark" data-controller="subscribe">
  <h3 class="text-center">SIGN UP FOR GETBUY WEEKLY</h3>
  <div class="input-group mb-3">
    <input type="text" class="form-control" data-target="subscribe.email" style="font-family: FontAwesome;" placeholder='&#xf0e0 ENTER YOUR EMAIL' aria-label="Recipient's username"
      aria-describedby="button-addon2">
    <div class="input-group-append">
      <button class="btn btn-outline-secondary" data-action="subscribe#add" type="button" id="button-addon2">GET IT IN YOUR INBOX</button>
    </div>
  </div>
</section>

app/views/shared/frontend/_top_menu.html.erb
<ul class="nav justify-content-center p-2">
  <% categories.each do |category| %>
  <li class="nav-item">
    <%= link_to category.name, category,class: "nav-link text-muted text-decoration-none" %>
  </li>
  <% end %>
</ul>