config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"

  resources :products
  resources :categories, only: [:show]
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete :cancel     # orders/id/cancel
      post :pay          # orders/id/pay
      get :pay_confirm   # orders/id/pay_confirm
    end
    
    collection do
      get :confirm       # orders/confirm
    end
  end

  namespace :admin do
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort
      end
    end
  end

  # api/v1/subscribe
  namespace :api do
    namespace :v1 do
      post :subscribe, to: "utils#subscribe"
      post :cart, to: "utils#cart"
    end
  end
end

app/views/shared/backend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-home"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Vendors", admin_vendors_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Products", admin_products_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Categories", admin_categories_path, class: "nav-link text-white" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <% if current_user.username? %>
            <%= current_user.username %>
          <% else %>
            <%= current_user.email.split('@').first %>
          <% end %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete,
                                data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    
  </div>
</nav>