config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"

  resources :products
  resources :categories, only: [:show]
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete :cancel     # orders/id/cancel
      post :pay          # orders/id/pay
      get :pay_confirm   # orders/id/pay_confirm
    end
    
    collection do
      get :confirm       # orders/confirm
    end
  end

  namespace :admin do
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort
      end
    end
  end

  # api/v1/subscribe
  namespace :api do
    namespace :v1 do
      post :subscribe, to: "utils#subscribe"
      post :cart, to: "utils#cart"
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def self.from_hash(hash = nil)
    # {
    #   "items" => [
    #     {"sku_id" => 1, "quantity" => 3},
    #     {"sku_id" => 2, "quantity" => 2}
    #   ] 
    # }

    if hash && hash["items"]
      items = hash["items"].map { |item|
        CartItem.new(item["sku_id"], item["quantity"])
      }
      Cart.new(items)
    else
      Cart.new
    end
  end

  def serialize
    items = @items.map { |item| {"sku_id" => item.sku_id, 
                                 "quantity" => item.quantity } }
    
    { "items" => items }
  end

  def add_sku(sku_id)
    found_item = items.find { |item| item.sku_id == sku_id }

    if found_item
      found_item.increment
    else
      @items << CartItem.new(sku_id)
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    #total = 0

    #@items.each do |item|
     #total += item.total_price
    #end

    #total
    @items.reduce(0) { |sum, item| sum + item.total_price }
  end

  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def show
  end

  def destroy
    session[:cart_9527] = nil
    redirect_to root_path, notice: "Cart Item deleted successfully."
  end

  def checkout
    @order = current_user.orders.build
  end
end

app/views/carts/_cart_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Mount</th>
    </tr>
  </thead>
  <tbody>
    <% current_cart.items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.product.sell_price %></td>
      <td><%= item.quantity %></td>
      <td><%= item.total_price %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan='3'><b>Total Price</b></td>
      <td><%= current_cart.total_price %></td>
    </tr>
  </tfoot>
</table>

app/views/carts/checkout.html.erb
<section class="container">
  <h1>Check Cart Item</h1>

  <%= render "cart_list" %>
  
  <h3 class="mt-5">Recipient Information</h3>
  <%= form_with model: @order do |f| %>
    <div class="form-row">
      <div class="col">
        <%= f.label :recipient %>
        <%= f.text_field :recipient, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :tel %>
        <%= f.text_field :tel, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :note %>
      <%= f.text_area :note, rows: 5, class: "form-control" %>
    </div>
    <div class="form-action">
      <%= f.submit "Use Line-Pay", class: "btn btn-info", data: { confirm: "Are you sure?" } %>
    </div>
    <% end %>
</section>

app/views/carts/show.html.erb
<section class="container">
  <h1>Cart</h1>
  <% unless current_cart.empty? %>
    <div>
      <%= link_to cart_path, class: "text-decoration-none", method: :delete, data: {confirm: "Are you sure?"} do %>
        <i class="far fa-trash-alt"></i>
        <span>Delete Items</span>
      <% end %>
    </div>
  <% end %>
  
  <% if current_cart.empty? %>
    <p>Please choose something</p>
    <%= link_to "Choose Item", root_path, class: "btn btn-info" %>
  <% else %>
    <%= render "cart_list" %>
    <%= link_to "Choose Item", root_path, class: "btn btn-info" %>
    <%= link_to "Pay", checkout_cart_path, class: "btn btn-danger" %>
    <% end %>
</section>