config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"

  resources :products
  resources :categories, only: [:show]
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete :cancel     # orders/id/cancel
      post :pay          # orders/id/pay
      get :pay_confirm   # orders/id/pay_confirm
    end
    
    collection do
      get :confirm       # orders/confirm
    end
  end

  namespace :admin do
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort
      end
    end
  end

  # api/v1/subscribe
  namespace :api do
    namespace :v1 do
      post :subscribe, to: "utils#subscribe"
      post :cart, to: "utils#cart"
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include CodeGenerator
  acts_as_paranoid
  
  has_rich_text :description
  has_one_attached :cover_image

  # Validations
  validates :name, presence: true
  validates :list_price, :sell_price, numericality: { greater_than: 0, allow_nil: true }
  validates :code, uniqueness: true

  # Relationships
  belongs_to :category, optional: true
  belongs_to :vendor
  has_many :skus
  accepts_nested_attributes_for :skus, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, only: [:edit, :update, :destroy]
  def index
    @products = Product.all.includes(:vendor)
  end

  def new
    @product = Product.new
    @product.skus.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Product created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to edit_admin_product_path(@product), notice: "Product updated successfully."
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, notice: "Product deleted successfully."
  end

  private

  def find_product
    @product = Product.friendly.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, 
                                    :vendor_id, 
                                    :list_price, 
                                    :sell_price, 
                                    :on_sell, 
                                    :code,
                                    :description,
                                    :cover_image,
                                    :category_id,
                                    skus_attributes: [
                                      :id, :spec, :quantity, :_destroy
                                    ])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(updated_at: :desc).includes(:vendor).with_attached_cover_image.with_rich_text_description_and_embeds
  end

  def show
    @product = Product.friendly.find(params[:id])
  end
end

app/views/admin/products/_form.html.erb
<section class="container">
  <%= form_with(model: [:admin, product]) do |f| %>
    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <%= f.label :cover_image, "The Main Picture" %>
          <%= f.file_field :cover_image %><br>
          <%= image_tag f.object.cover_image.variant(resize: '300x200') if f.object.cover_image.attached? %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <%= f.label :name, "Product Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col-3">
        <div class="form-group">
          <%= f.label :vendor_id, "Vendor" %>
          <%= f.collection_select :vendor_id, Vendor.available, :id, :title, { prompt: 'Select Vendor' }, { class: 'form-control' } %>
        </div>
      </div>
      <div class="col-3">
        <div class="form-group">
          <%= f.label :category_id, "Category" %>
          <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: 'Select Category' }, { class: 'form-control' } %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <%= f.label :list_price, "List Price" %>
          <%= f.number_field :list_price, class: "form-control" %>
        </div>
      </div>
      <div class="col-6">
        <div class="form-group">
          <%= f.label :sell_price, "Selling Price" %>
          <%= f.number_field :sell_price, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">    
      <div class="col-12">
        <div class="form-check">
          <%= f.check_box :on_sell, class: "form-check-input" %>
          <%= f.label :on_sell, class: "form-check-label" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Product Description" %>
          <%= f.rich_text_area :description %>
        </div>

        <hr>
        <div class="form-group">
          <h3>Stock Items</h3>
          <div data-controller="product-form">
            <template data-target="product-form.template">
              <%= f.fields_for :skus, Sku.new, child_index: "NEW_RECORD" do |sku| %>
                <%= render 'sku_fields', form: sku %>
              <% end %>
            </template>

            <%= f.fields_for :skus do |sku_form| %>
              <%= render 'sku_fields', form: sku_form %>
            <% end %>
          
            <div data-target="product-form.link">
              <%= link_to "Add New Spec", '#', data: { action: "product-form#addSku" },
                                              class: "btn btn-secondary btn-sm" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit (f.object.new_record? ? 'Create New Product' : 'Update Product'), class: "btn btn-info" %>
        </div>
      </div>
    </div>
  <% end %>
</section>
  

app/views/admin/products/_sku_fields.html.erb
<div class="row mb-3 nested-fields" data-new-record="<%= form.object.new_record? %>">
  <div class="col-8">
    <%= form.text_field :spec, placeholder: "Spec", class: "form-control" %>
  </div>
  <div class="col-3">
    <%= form.number_field :quantity, placeholder: "Quantity", class: "form-control" %>
  </div>
  <div class="col-1">
    <%= link_to "Delete", '#', class: "btn btn-danger",
                               data: { action: "product-form#removeSku" } %>
  </div>
  <%= form.hidden_field :_destroy %>
</div>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

app/views/admin/products/index.html.erb
<section class="container">
  <h1>Product Lists</h1>
  <%= link_to "Create New Product", new_admin_product_path, class: "btn btn-info" %>
  <table class="table">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Vendor</th>
        <th>Price</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= link_to "#{product.name} [ProductCode: #{product.code}]", edit_admin_product_path(product) %></td>
        <td><%= product.vendor.title %></td>
        <td><%= product.list_price %>/<%= product.sell_price %></td>
        <td><%= product.on_sell %></td>
        <td>
          <%= link_to "edit", edit_admin_product_path(product), class: "btn btn-secondary btn-sm" %>
          <%= link_to "Delete", admin_product_path(product), method: :delete,
                                data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</section>

app/views/admin/products/new.html.erb
<h1>Create New Product</h1>

<%= render 'form', product: @product %>